spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpatest
    username: root
    password: 8834
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
#        default_batch_fetch_size: 1000