spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
  datasource:
    password: 8834
    username: root
    url: 'jdbc:postgresql://localhost:5432/jpa_update'