server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: 192.168.56.101:9092
  config:
    import: optional:configserver:http://127.0.0.1:8081
  application:
    name: user, common
  profiles:
    active: dev

  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh


